language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
script:
  - echo "skipping tests"
deploy:
  provider: script
  script: yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master